// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sultana.API.Data;

#nullable disable

namespace Sultana.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sultana.Shared.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.ConsumoMP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CantidadUsada")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoteMateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoteMateriaPrimaId");

                    b.HasIndex("OrdenProduccionId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("ConsumoMPs");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.LoteMateriaPrima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CantidadIngresada")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("EstadoEmpaque")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaHoraRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspeccionColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InspeccionOlor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InspeccionTextura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("MateriaPrimaId", "NumeroLote")
                        .IsUnique();

                    b.ToTable("LoteMateriaPrimas");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.LoteProductoTerminado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaVencimientoPT")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockPT")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenProduccionId")
                        .IsUnique();

                    b.ToTable("LoteProductoTerminados");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.MateriaPrima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MateriaPrimas");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadPeso")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoPT")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoteProducto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("ProductoTerminadoId", "LoteProducto")
                        .IsUnique();

                    b.ToTable("OrdenProducciones");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.ProductoTerminado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ProductoTerminados");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NombreVendedor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.VentaCabecera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Factura")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("VentaCabeceras");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.VentaDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("LoteProductoTerminadoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaCabeceraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoteProductoTerminadoId");

                    b.HasIndex("VentaCabeceraId");

                    b.ToTable("VentaDetalles");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.ConsumoMP", b =>
                {
                    b.HasOne("Sultana.Shared.Entities.LoteMateriaPrima", "LoteMateriaPrima")
                        .WithMany("Consumos")
                        .HasForeignKey("LoteMateriaPrimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Consumos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.Empleado", "Responsable")
                        .WithMany("Consumos")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteMateriaPrima");

                    b.Navigation("OrdenProduccion");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.LoteMateriaPrima", b =>
                {
                    b.HasOne("Sultana.Shared.Entities.MateriaPrima", "MateriaPrima")
                        .WithMany("Lotes")
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.Proveedor", "Proveedor")
                        .WithMany("LotesSuministrados")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.Empleado", "Responsable")
                        .WithMany("LotesRecibidos")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("Proveedor");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.LoteProductoTerminado", b =>
                {
                    b.HasOne("Sultana.Shared.Entities.OrdenProduccion", "OrdenProduccion")
                        .WithOne("LotePT")
                        .HasForeignKey("Sultana.Shared.Entities.LoteProductoTerminado", "OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.OrdenProduccion", b =>
                {
                    b.HasOne("Sultana.Shared.Entities.ProductoTerminado", "ProductoTerminado")
                        .WithMany("Ordenes")
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.Empleado", "Responsable")
                        .WithMany("Ordenes")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoTerminado");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.VentaCabecera", b =>
                {
                    b.HasOne("Sultana.Shared.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.Empleado", "Responsable")
                        .WithMany("VentasAtendidas")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.VentaDetalle", b =>
                {
                    b.HasOne("Sultana.Shared.Entities.LoteProductoTerminado", "LoteProductoTerminado")
                        .WithMany("Ventas")
                        .HasForeignKey("LoteProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sultana.Shared.Entities.VentaCabecera", "VentaCabecera")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaCabeceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteProductoTerminado");

                    b.Navigation("VentaCabecera");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.Empleado", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("LotesRecibidos");

                    b.Navigation("Ordenes");

                    b.Navigation("VentasAtendidas");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.LoteMateriaPrima", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.LoteProductoTerminado", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.MateriaPrima", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.OrdenProduccion", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("LotePT");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.ProductoTerminado", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.Proveedor", b =>
                {
                    b.Navigation("LotesSuministrados");
                });

            modelBuilder.Entity("Sultana.Shared.Entities.VentaCabecera", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
